In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
type(a)


[1 2 3 4]


numpy.ndarray

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
type(a)
a.ndim


[[1 2 3 4]
 [5 6 7 8]]


2

In [ ]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(a)
print(type(a))
print(a.size)
a.ndim


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
<class 'numpy.ndarray'>
12


3

In [ ]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
a=np.zeros(4,dtype=int)
a
a.size
a.shape

(4,)

In [ ]:
a=np.zeros((3,4))
a
a.size
a.shape

(3, 4)

In [ ]:
a=np.zeros((3,4),dtype=int)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
12
(3, 4)
2


numpy.ndarray

In [ ]:
a=np.zeros((2,3,4))
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
24
(2, 3, 4)
3


numpy.ndarray

In [ ]:
a=np.ones(3)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)

[1. 1. 1.]
3
(3,)
1


numpy.ndarray

In [ ]:
a=np.ones(1,dtype=int)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)

[1]
1
(1,)
1


numpy.ndarray

In [ ]:
a=np.ones([3,4])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12
(3, 4)
2


numpy.ndarray

In [ ]:
a=np.ones([3,4,5],dtype=int)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
60
(3, 4, 5)
3


numpy.ndarray

In [ ]:
a=np.full(3,9,dtype=str)
print(a)
a=np.ones([3,4,5],dtype=int)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)


['9' '9' '9']
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
60
(3, 4, 5)
3


numpy.ndarray

In [ ]:
a=np.full([2,3],9)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)


[[9 9 9]
 [9 9 9]]
6
(2, 3)
2


numpy.ndarray

In [ ]:
a=np.full([4,2,3],10,dtype=str)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
type(a)


[[['1' '1' '1']
  ['1' '1' '1']]

 [['1' '1' '1']
  ['1' '1' '1']]

 [['1' '1' '1']
  ['1' '1' '1']]

 [['1' '1' '1']
  ['1' '1' '1']]]
24
(4, 2, 3)
3


numpy.ndarray

NUMPY ADDITION

In [ ]:
a=np.array([1,2,3])
b=np.array([0,0,0])
add=np.add(a,b)
add

array([1, 2, 3])

subtraction


In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,5])
sub=np.subtract(a,b)
sub

array([ 0,  0, -2])

In [ ]:
a=np.array([1,2,3])
b=np.array([0,0,0])
mul=np.multiply(a,b)
mul

array([0, 0, 0])

In [ ]:
a=np.array([1,2,3])
b=np.array([0,0,0])
div=np.divide(a,b)
div


<ipython-input-53-28d78eb5d211>:3: RuntimeWarning: divide by zero encountered in divide
  div=np.divide(a,b)


array([inf, inf, inf])

In [ ]:
a=np.array([10000,200000,300000])
b=np.array([10,100,1000])
mo=np.mod(a,b)
mo

array([0, 0, 0])

In [ ]:
a=np.array([1,2,3])
b=np.array([0,0,0])
p=np.power(a,b)
p

array([1, 1, 1])

DATA VISUALISATION